# Generated by Django 5.1.2 on 2024-11-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
