# Generated by Django 5.1.2 on 2024-11-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='subcategory',
        ),
    ]
